
EMWI_GFX_FILES :=                                                              \
                    ewextgfx.c                                                 \
                    ewextbmp_RGB565.c                                          \
                    ewextfnt.c                                                 \
                    ewextpxl_RGB565.c                                          \
                    ewgfx.c                                                    \
                    ewgfxattrtext.c                                            \
                    ewgfxbidi.c                                                \
                    ewgfxcore.c                                                \
                    ewgfxdriver.c                                              \
                    ewgfxtasks.c                                               \

