
EMWI_RTE_FILES :=                                                              \
                    ewextrte.c                                                 \
                    ewcolor.c                                                  \
                    ewdebug.c                                                  \
                    ewheap.c                                                   \
                    ewobject.c                                                 \
                    ewpoint.c                                                  \
                    ewrect.c                                                   \
                    ewref.c                                                    \
                    ewresource.c                                               \
                    ewscalars.c                                                \
                    ewslot.c                                                   \
                    ewstring.c                                                 \
                    ewtimer.c                                                  \

